services:
  web:
    image: "dhis2/core:${DHIS2_VERSION:-2.41}"
    ports:
      - "8080:8080"
    volumes:
      - ./conf/dhis.conf:/opt/dhis2/dhis.conf:ro
      - ./conf/log4j2.xml:/opt/dhis2/log4j2.xml:ro
    environment:
      JAVA_OPTS: "-Dlog4j2.configurationFile=/opt/dhis2/log4j2.xml"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dhis2-net

  db:
    image: "ghcr.io/baosystems/postgis:${POSTGRES_VERSION:-13-3.4}"
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dhis}
      POSTGRES_DB: ${POSTGRES_DB:-dhis}
      POSTGRES_PASSWORD: &postgres_password ${POSTGRES_PASSWORD:-dhis}
      PGPASSWORD: *postgres_password
    healthcheck:
      test: [ "CMD-SHELL", "psql --no-password --quiet --username $$POSTGRES_USER postgres://127.0.0.1/$$POSTGRES_DB -p 5432 --command \"SELECT 'ok'\" > /dev/null" ]
      start_period: 300s
      interval: 5s
      timeout: 5s
      retries: 60
    networks:
      - dhis2-net

networks:
  dhis2-net:
    driver: bridge