name: Test DHIS2 Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-dhis2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh && echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: set up python
      run: uv python install
    - name: install project
      run: uv sync --locked --dev
    - name: start dhis2
      working-directory: dhis2
      run: uv run start_dhis2.py
    - name: run tests
      run: uv run pytest tests/
    - name: show container logs on failure
      if: failure()
      run: |
        echo "=== Web container logs ==="
        docker compose -f dhis2/docker-compose.yml logs web
        echo "=== DB container logs ==="
        docker compose -f dhis2/docker-compose.yml logs db
    - name: cleanup
      if: always()
      working-directory: dhis2
      run: docker compose -f docker-compose.yml down -v
